secretsprovider: azurekeyvault://kv-banana-pulumistate.vault.azure.net/keys/encryptionState
encryptedkey: Y2ZlX09wdTVRNm9OREZNRGN5eGxMZVhJZm1BazBaQ2VfLUhKbnpmM1pkblo5OE5LSHNVUzZhTWpzbUUzR0RpOU9DQUtmMlpVTVFCMTlEa3dQdVdlV0R3VFZSR1dRUWNvWkFQMDFMamc0Y0lhNEoxWmphQU9CWTA0bi1uMVloQlpRWjdKbDNUM0cya1Rmck9yTDNFRi14dEtmek9GeDZoN210UF9DdGRDQjlicm1fZjVKY20tbDVtVWxycmw4dFJncGRwOGdrYklHNUhjbjB2TFJETWM2U0tUYV96RDhyeDloQ3hWWXA5ZE4zS3ZzM2dVcmt6RUpMWUlqS1I5Y1hTSUVMdnczUzJMNlZDREVZWXA5UTROdS15MEd2T210VGJtd0RkUzhaZV9uS2drdzZ1SUxRVnhjeWN0SS1xVjc1SUctNk8tT0lHdnhXaHhEbW9OVk5hZkFR
config:
  AzureStorageBackend:funky:
    secure: v1:B9GsRwNHiuANfLOn:u2a2e4aSO7aJXxONwS5vMhE6qoo=
  AzureStorageBackend:funkysef:
    secure: v1:qjO4tjh00uI0bWTR:OqCPgGypFrhnAp7JhK2rrGi4xxk=
  AzureStorageBackend:funkyseseff:
    secure: v1:7uoGU1JGT6mxjld5:4Cy2so5suqJSUt91SSo1mCYWIiX1pdpB
  azure-native:location: australiaeast
