name: Pulumi-Preview
on:
  - pull_request
  - workflow_dispatch
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Connect To Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS}}
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: org-name/stack-name # When using an individual account, only use stack-name.
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL}}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}